execute @s[scores={ICM=0}] ~~~ function toggle/itemcommand
execute @s[scores={ACM=0}] ~~~ function toggle/anticbe
execute @s[scores={AFM=0}] ~~~ function toggle/antifly
execute @s[scores={UOIM=0}] ~~~ function toggle/unobtainableitems
execute @s[scores={LTM=0}] ~~~ function toggle/lagclear
execute @s[scores={HMM=0}] ~~~ function toggle/hotbarmessage
execute @s[scores={NFM=0}] ~~~ function toggle/nofrostwalker
execute @s[scores={TPM=0}] ~~~ function toggle/timeplayed
execute @s[scores={MDM=0}] ~~~ function toggle/mining_detection
execute @s[scores={SSM=0}] ~~~ function toggle/stafftag
execute @s[scores={OPAM=0}] ~~~ function toggle/opabuse
execute @s[scores={OSM=0}] ~~~ function toggle/anti_oneshot