#bridge-file-version: #31
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§c《--- Astro Staff Commands (Caps Sensitive) ---》"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ USER MANUAL : §6(SITE LINK)"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Stats     §2- /execute (player) ~~~ function Astro/stats"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Stats: §2Shows player's time played, warns, and current gamemode"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Warn:     §2- /execute (player) ~~~ function Astro/warn"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Warn Reset§2- /execute (player) ~~~ function Astro/warnreset"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Punish    §2- /execute (player) ~~~ function Astro/punish"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Punish:§2 This clears Inv and Echest then gives warning"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Ban       §2- /tag (player) add Ban"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Unban     §2- /execute (player) ~~~ function Astro/unban"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Freeze       §2- /function Astro/freeze_player"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Unfreeze       §2- /function Astro/freeze_player"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Disable PvP       §2- /function Astro/pvpdisable"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Enable PvP       §2- /function Astro/pvpdisable"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Clear Lag §2- /function Astro/lagclear"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Clear Large Area§2- /function Astro/cleararealarge"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Clear Small Area§2- /function Astro/clearareasmall"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Clear Storage Blocks§2- /function Astro/clearareastorage"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Godmode   §2- /function Astro/tgm"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Vanish   §2- /function Astro/vanish"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Modules   §2- /function Astro/modulecheck"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Itembans  §2- /function Astro/itembancheck"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§c==== Custom Toggles ===="}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Toggle Modules    §2- /function toggle"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Toggle Banned Items   §2- /function banitem"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§b→ Toggle WorldBorder Size   §2- /function worldborder"}]}
tellraw @s[tag=stafftag] {"rawtext":[{"text":"§¶§c《---------------------------------》"}]}
execute @s[tag=stafftag] ~~~ playsound note.pling @s ~ ~ ~
execute @s[tag=!stafftag] ~~~ playsound note.bass @s ~ ~ ~
execute @s[tag=!stafftag] ~~~ tellraw @s {"rawtext":[{"text":"§¶§cAstro → §bYou must be staff to do this command. The tag for staff is §6stafftag"}]}
execute @s[tag=stafftag] ~~~ function Astro/asset/version
execute @s[tag=stafftag] ~~~ function Astro/asset/discord
execute @s[tag=stafftag] ~~~ function Astro/asset/createdby
